### PR TITLE
[WIP] Support local packages

### PR DESCRIPTION
**Pull request by andychase**
One issue I had working with a customer is that they needed to install a binary local package but also wanted to use CRAN for the rest of their packages. The current system is either all or nothing, either use a local CRAN, or a mirror, you can't mix and match.

I implemented a quick fix using the included patch but I am looking for feedback on how to better support this in the R buildpack. What should the `r.yml` syntax be?

### CODE REVIEW

**Comment by menehune23** [comment]
Hi @andychase Is this still a WIP?

**Comment by andychase** [comment]
I was hoping you would give feedback, but happy to pass it over to you as
well

**Comment by menehune23** [comment]
@andychase I'd say that feedback would be a regular part of the PR process anyway. When you have some time, go ahead and cover these changes with unit and acceptance tests, un-WIP it, and we'll take a look when get can.

**Comment by andychase** [comment]
This approach ended up being unreliable; going to try using the apt-buildpack instead. Although I've already run into a problem which is that the apt packages are built using the system version of R which is 3.6.x

**Comment by andychase** [comment]
Yeah using the apt buildpack didn't work since the versions weren't compatible with the list of supported versions here. I found this solution: https://github.com/cloudfoundry/r-buildpack/issues/12

Although it's not great. I'm hoping there's a better solution. Maybe raise the build timeout

**Pull request closed without merging**
