### PR TITLE
Feature/vendoring packages support

### PR DESCRIPTION
**Pull request by venkatk-25**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by venkatk-25** [comment]
@sclevine I have made the changes requested.

**Comment by sclevine** [comment]
Looks great! Let us know when you've signed the CLA.

**Comment by chipchilders** [comment]
close / open to bump CLA bot

**Comment by chipchilders** [comment]
close / open to bump CLA bot

**Comment by chipchilders** [comment]
@sclevine something is odd with dreddbot... will ping toolsmiths team. That said, this PR is OK from a CLA perspective. We have a CLA from @venkatk-25

**Comment by chipchilders** [comment]
@sclevine @venkatk-25 I noted that there is a commit from @astrieanna in the commit log... that may be the issue.

**Comment by venkatk-25** [comment]
@chipchilders thanks for identifying, looks like I raised the pull request against wrong batch
@sclevine I have raised raised the request against right branch and CLA looks good now.

**Comment by sclevine** [comment]
Apologies for the delay in merging this. This PR looks great. We'll take care of any additional changes.

**Comment by sclevine** [comment]
@venkatk-25 this is on the `develop` branch. Note that we went with `vendor` instead of `rPackages` to match CF buildpack convention.

**Comment by venkatk-25** [comment]
@sclevine Thanks for merging. I named it with a different name intentionally, because it is confusing in multi-buildpack scenario when you want to vendor multiple languages. 

Anyway, closing the pull request now that it is merged.

**Pull request closed without merging**
